src/Bloc-Text-Elements.package/BlTextEditListener.class/instance/moveCursorLeft.by..st
BlTextEditListener >> moveCursorLeft:by: refered to "right" in multiple places, probably from copying the method moveCursorRight:by:
The incorrect condition to transfer focus out of the element prevented the cursor from moving left of the second element.
Maybe I'm misunderstanding and this is actually correct and will break other stuff, but it seems odd.
=> Fix cursor movement in BlTextEditListener

src/BlocHost-Morphic/BlExternalForm.class.st
Such vm will be promoted to stable at some point.
The problem is that this is not back-wards compatible and
so can break 80+vm and 90+vm.
Pair-programmed with Pablo Tesone.
BlExternalForm is now subclass of OSSDL2ExternalForm,
and we remove redundant methods, and "primitives".
Fixes #109
=> Prepare for Pharo 9 with latest vm

src/BlocHost-OSWindow-SDL2/BlOSWindowSDL2Renderer.class.st
If the SDL_Renderer is not destroyed at this point, it will be destroyed by 
the finalization process (GC), when the SDL_Window was alrerady 
destroyed, which is detected by several asserts in the SDL library.
Thanks @tesonep for pair-programming.
Fixes #120
=> BlOSWindowSDL2Renderer must destroy the renderer

src/Bloc-Spec2-Tests/SpBlSpaceInMorphPresenterTest.class.st, src/Bloc-Spec2/SpBlSpaceInMorphPresenter.class.st
It provides a space that is already shown using a `BlMorphicHost`, to embed it in a `Morph`, which is added via `SpMorphPresenter`.
=> Add a Spec2 presenter with a Bloc space ready to work.

src/Bloc-PullAndSlide/BlPullEvent.class.st, src/Bloc-PullAndSlide/BlPullHandler.class.st
* Pull handler:
- remove relocateX and Y (was too confusing)
- rename targetElement: to target: 
* BlPullEvent:
- add class comment
- full change in API: names were confusing, and not used. Now the event knows current position and initial position and seems to be fine.
Why? check the following users of this change:
- https://github.com/plantec/OnBloc/pull/4
- https://github.com/plantec/Toplo/pull/34
=> Pass on pull handler

src/Bloc-Layout-Tests/BlProportionalLayoutTest.class.st, src/Bloc-Layout/BlProportionalLayout.class.st, src/Bloc-Layout/BlProportionalLayoutConstraints.class.st, src/Bloc-Layout/BlProportionalLayoutConstraintsHorizontal.class.st, src/Bloc-Layout/BlProportionalLayoutConstraintsVertical.class.st, src/Bloc/BlBounds.class.st, src/Bloc/BlLayoutCommonConstraints.class.st
Fixes #260
Note: It still doesn't take into account minWidth and minHeight. It should, right?
Also, eventually a negative extent.
So another commit must work on those.
=> Add proportional layout and tests

src/Bloc-Demo/BlDemoApplication.class.st, src/Bloc-Demo/BlDemoPresenter.class.st, src/Bloc-Demo/BlDemoTransmissionPresenter.class.st, src/Bloc-Demo/package.st
Hello, 
I wanted to try and create a Demo Browser with Spec2. It aims to display some example classes you can browse and display their methods code while showing the graphical result in a Space nearby. Here's a screenshot : 
The Demo Browser can be opened executing 
```smalltalk 
BlDemoPresenter new open
```
I think this could be a great addition to Bloc and I would have loved having this at the beginning to understand Bloc basics.
This is the very first iteration as it is my first project with Spec2 but I'm proud of it. Also I wanted to share it early so this could be improved in early development. 
For now it browses through `BlExampleTest` subclasses as I saw most of available examples inherits this class but many methods return objects that are not `BlElement` so for now, for those …
=> Created a small Demo browser

src/Bloc/BLCursor.class.st
Fixes #403 
Sorry for the inconvenance
=> Add back BLCursor as deprecated

src/Bloc-Alexandrie/BlCompositeBackground.extension.st, src/Bloc/BlCompositeBackground.class.st
This change cleans a little BlCompositeBackground
- Avoid to copy collections twice in #withAll:
- Do not initialize with an empty collection since all users are updating this collection later
- Use getter
- Remove an abbreviation to use something more readable
- Improve the rendering of the class comment
Fixes #366
=> Little cleaning of BlCompositeBackground

src/BlocHost-Morphic/BlMorphicHostSpace.class.st, src/BlocHost-Morphic/BlMorphicSpaceHostMorph.class.st
This pull request makes `#physicalSize` on BlMorphicHostSpace apply the world renderer canvas scale factor. For details see issue #450.
Note that this pull request depends on changes in Pharo 12, specifically the class FormSet introduced in [Pharo pull request #14998](https://github.com/pharo-project/pharo/pull/14998) and the method `#canvasScaleFactor` for OSWorldRenderer introduced in [Pharo pull request #15647](https://github.com/pharo-project/pharo/pull/15647).
=> Make #physicalSize on BlMorphicHostSpace apply the world renderer canvas scale factor

src/Bloc/BlDelayPulsesTask.class.st
See https://github.com/pharo-graphics/Bloc/pull/482
=> Deprecate BlDelayPulsesTask since it's not used and its purpose was debugging

src/Bloc-DevTool/BlSelectionTool.class.st, src/Bloc-PullAndSlide/BlScrollSlideHandler.class.st, src/Bloc-PullAndSlide/BlSlideHandler.class.st, src/Bloc/BlEvent.class.st, src/Bloc/BlSelectionHandler.class.st, src/Bloc/BlShortcutHandlerWithShortcuts.class.st
@plantec WDYT about adding this `aBlEvent consume` to do the same as `aBlElement consumed: true`?
In my image, I had 87 senders of `consumed:` and almost all of them have true as argument
=> Add BlEvent>>consume that is equivalent to consume: true

src/Bloc-Tests/BlEventTest.class.st
- Fixes #498
- Fix test on overlapped elements with elevation
- Remove returns since they make code obscure
- Rename tests that were in fact helpers (not tests) 
- Remove pragmas
=> Pass on BlEventTest

src/BaselineOfBloc/BaselineOfBloc.class.st, src/Bloc-Rules/ReBlocDoNotSendForceLayoutRule.class.st, src/Bloc-Rules/ReBlocWidthShouldNotBeOverriddenRule.class.st, src/Bloc-Rules/package.st
Fixes: #474 add a package with some rules and update the baseline
=> Fixes: #474 add a package with some rules and update the baseline

src/Bloc-Taskit-Tests/TKTBlocExamples.class.st, src/Bloc-Taskit-Tests/TKTBlocTest.class.st, src/Bloc-Taskit-Tests/package.st, src/Bloc-Taskit/TKTBlSpaceRunner.class.st, src/Bloc-Taskit/TKTBlSpaceService.class.st, src/Bloc-Taskit/package.st
Created with Pablo last week.
Demo script:
```smalltalk 
space := BlSpace new.
space
useMorphicHost;
extent: 200@200;
show.
"action 1"
space enqueueTask:
(BlTaskAction new
action: [ space root background: Color random ];
yourself).
"action 2"
runner := TKTBlSpaceRunner on: space.
runner schedule: [ space root background: Color random ] asTask.
"repeatable 1"
space enqueueTask:
(BlRepeatedTaskAction new
delay: 250 milliSeconds;
action: [ space root background: Color random ];
yourself).
"repeatable 2"
service := TKTParameterizableService new.
service name: 'Change background'.
service step: [
space enqueueTask: (BlTaskAction new
action: [space root background: Color random ];
yourself) ].
service stepDelay: 250 milliSeconds.
service start.
"service stop."
```
=> Add convenience objects to use taskit in Bloc

src/Bloc-Alexandrie/BlRoundedPolygonGeometry.extension.st, src/Bloc/BlRoundedPolygonGeometry.class.st
Fixes issue #451
TO DO:
- tests needed
- containsPoint: is not precise
- we should cache some calculated values, to avoid repeating the same maths on every new frame
- this is the closed polygon, it's a pity we don't support being an open geometry (a "polyline")
- we may decide to do some refactorings such as merge it with it's superclass
=> Add BlRoundedPolygonGeometry

src/BlocHost-Morphic/BlMorphicHostSpace.class.st, src/BlocHost-Morphic/BlMorphicSpaceHostMorph.class.st
This pull request applies the changes of pull request #465 to the ‘Pharo12’ branch. The two SystemVersion checks could presumably be dropped, but I kept them to not deviate from the implementation in the ‘dev’ branch.
=> Apply application of world renderer canvas scale factor in #physicalSize on BlMorphicHostSpace to Pharo 12

src/Bloc-Alexandrie-Exporter/BAExporter.class.st, src/Bloc-Alexandrie/BlElement.extension.st, src/Bloc/BlElement.class.st
With this PR merged, we mitigate what is reported in #561 which is in fact not specific to proportional layout, but to the race condition on computation of layouts (#560).
A way to mitigate (workaround) the race condition is this:
```smalltalk
a := (BlElement new
id: #A;
background: Color red;
constraintsDo: [:constraints |
constraints horizontal matchParent.
constraints vertical matchParent.
constraints padding: (BlInsets all: 20.0) ];
layout: BlFrameLayout new;
addChild: (BlElement new
id: #B;
background: Color green;
effect: (BlSimpleShadowEffect
color: Color white
offset: 5 @ 15);
constraintsDo: [:constraints |
constraints vertical matchParent.
constraints horizontal exact: 200.
constraints frame horizontal alignCenter.
constraints padding: (BlInsets all: 20.0) ];
layout: …
```
=> Fix some bugs in export to Form

src/Bloc-Examples/BlClickEventTest.class.st, src/Bloc-Examples/BlElementBoundsByScripterTest.class.st, src/Bloc-Examples/BlEventCountingElement.class.st, src/Bloc-Examples/BlFocusProcessorTest.class.st, src/Bloc-Examples/BlMouseEventTest.class.st, src/Bloc-Examples/BlMouseProcessorClickTest.class.st, src/Bloc-Examples/BlMouseProcessorEnterLeaveTest.class.st, src/Bloc-Examples/BlMouseProcessorTest.class.st, src/Bloc-Examples/BlMouseWheelEventTest.class.st, src/Bloc-Examples/BlSharedEventDistributorTest.class.st, src/Bloc-Examples/BlSpaceEventTest.class.st, src/Bloc/BlBaseDragEvent.class.st, src/Bloc/BlMouseProcessor.class.st
Hello, 
I refactored some tests on `BlMouseProcessor`
I separated in different tags the Event tests that were written with `assert:` and other written using a Scripted so we can work better if needing to change or delete the `BlDevScripter` class
Regards,
Enzo
=> Refactoring event Tests

src/BlocHost-Morphic/BlMorphicSpaceHostMorph.class.st
This pull request makes `#processEvent:using:` on BlMorphicSpaceHostMorph pass special gesture mouse events to the inherited implementation, so that halos can be opened on a space host morph:
<p align="center">
</p>
=> Make #processEvent:using: on BlMorphicSpaceHostMorph pass special gesture mouse events to the inherited implementation

src/Bloc-Layout-Tests/BlProportionalLayoutTest.class.st, src/Bloc-Layout/BlProportionalLayout.class.st
Notes:
* It was working in the inverse way.
* Fixes #562
* This change required updating a test.
* The layout class comment was outdated. Fixed too.
=> Proportional layout: Apply children margin after applying the proportions

src/Bloc-DevTool/BlDemoScript.class.st
This pull request adds BlDemoScript, a subclass of ClyClassScript, to allow class methods with a pragma ‘<demo>’ to be executed in a browser.
=> Add BlDemoScript to allow class methods with a pragma ‘<demo>’ to be executed in a browser

src/BlocHost-Morphic/BlMorphicWindowHostSpace.class.st
This pull request makes #physicalSize on BlMorphicWindowHostSpace apply the world renderer canvas scale factor. This is the same change as previously applied to BlMorphicHostSpace in pull request #465.
=> Make #physicalSize on BlMorphicWindowHostSpace apply the world renderer canvas scale factor

src/Bloc-Infinite/BlInfiniteMouseScrollListener.class.st, src/Bloc/Bloc.class.st
The settings belong to a Bloc-Infinite's class, so move it there.
Fixes #599
=> Move system settings to the corresponding package

src/Bloc/BlMouseDownEvent.class.st, src/Bloc/BlMousePickOutsideEvent.class.st, src/Bloc/BlMouseUpEvent.class.st
It sends an unimplemented selector and both subclasses override it.
Fixes #590
=> Remove BlMousePickOutsideEvent>>sendTo:

src/Bloc/BlBasicEventHandler.class.st
It is evidently a hook, but it is not overriden.
In fact it is sent, but only by SpPresenter (spec).
Fixes #628
=> Remove unsent BlBasicEventHandler>>#hasOwner

src/Bloc-Layout/BlGridLayoutImpl.class.st, src/Bloc-Layout/BlLinearLayoutHorizontalOrientation.class.st, src/Bloc-Layout/BlLinearLayoutVerticalOrientation.class.st, src/Bloc/BlElement.class.st, src/Bloc/BlLayout.class.st
=> BlElement: Deprecate outsets by margin & insets by padding

src/Bloc/BlMatrix.class.st, src/Bloc/BlMatrix2D.class.st, src/Bloc/BlMatrix3D.class.st, src/Bloc/BlMatrixDecomposition.class.st, src/Bloc/BlMatrixDecomposition2D.class.st
* asMatrixCollection was only used from printOn:. I rewrote it to print directly.
* The real use was as internal state of BlMatrixDecomposition2D, to store (sx, sy, shx, shy) values in some maths for interpolation. I rewrote the code to directly reference those 4 values instead of the Array2D.
See #643
=> Avoid using Array2D since it's deprecated in Pharo 12

.ci.ston, src/Bloc-Examples/BlElementBoundsByScripterTest.class.st, src/Bloc-Text-Examples/BlTextIteratorExamplesTest.class.st
These packages are being excluded:  'Bloc-Examples.*', 'Bloc-Layout-Examples.*', 'Bloc-Text-Examples.*'
I guess this fixes #376
=> CI: run all test packages

src/Bloc/BlSpace.class.st
Fixes #148
An old issue! accessors do not exist anymore, nor hierarchy of recorders, but still an instvar was present on space.
=> Remove last remains of event recorders

src/Bloc/BlHostRendererBufferSurface.class.st, src/BlocHost-OSWindow-SDL2/BlOSWindowSDL2BufferSurfaceRenderer.class.st
This should fix #688, as it avoids accessing the pixels of the SDL_Surface.
This is offtopic: changing SDL_TEXTUREACCESS_STREAMING by SDL_TEXTUREACCESS_STATIC... but in my bechmarks, STATIC is slightly faster.
=> Avoid creation of SDL_Surface, as we only need a ByteArray.

src/BlocHost-Morphic/BlMorphicSteppingHost.class.st
Morphic hosts register as stepping morphs then they must implement `#delete`.
Fixes #785. Thanks @LabordePierre for the report and fix.
=> Morphic hosts need to implement delete
