.smalltalk.ston

Following up on https://github.com/hpi-swa/smalltalkCI/issues/236.

Enable coverage testing again

---

src/Bloc/BlParallelUniverse.class.st
src/Bloc/BlSpace.class.st
src/BlocHost-Morphic/BlMorphicWindow.class.st
src/BlocHost-Morphic/BlMorphicWindowHostSpace.class.st
src/BlocHost-OSWindow-SDL2/OSSDL2BackendWindow.extension.st
src/BlocHost-OSWindow/BlOSWindowSpace.class.st
src/BlocHost-OSWindow/OSWindow.extension.st

Used by Spec-Brick bindings. No tests for the moment, but it's working in both hosts on Mac.

Add BlSpace>>center

---

src/BaselineOfBlocExtensions/BaselineOfBlocExtensions.class.st

it updates BaselineOfBlocExtensions to depend on NewBloc

Baseline of bloc extension

---

src/Bloc-Text/BlText.class.st

fixes issue #175

---

.gitattributes
src/Bloc-Tests/BlElementAlignableTest.class.st
src/Bloc-Tests/TBlAlignableTest.class.st
src/Bloc/TBlAlignable.trait.st

+ add a .gitattributes file to manage EOF encoding between Windows and others OS

TBlAligment : add "is" testing methods for each states of the aligment + add unit tests

---

src/Bloc-Tests/BlElementTest.class.st
src/Bloc/BlElement.class.st

Complete getting child and write some tests

---

src/Bloc-UnitedTests/BlElementChildrenTest.class.st
src/Bloc/BlElement.class.st

+ Fix for https://github.com/pharo-graphics/Bloc/issues/205
+ adding tests for all the methods for children accessing.
One of the test of the previous PR was not correct. It was `#testAllParentsUpToDo`.
It was a typo when i created the method `#testWithAllParentsUpToDo`. I started editing `#testAllParentsUpToDo` but i didn't give it the right name. I changed the name but forget to delete the `#testAllParentsUpToDo`.

Issue205 - Adding tests for children accessing methods

---

src/Bloc-UnitedTests/BlVectorTest.class.st
src/Bloc/BlVector.class.st

BlVector: Convert class-instance variables to class variables

---

src/Bloc-Examples/BlBasicExamples.class.st
src/Bloc-Examples/BlGeometryVisualAndLayoutBoundsExamples.class.st
src/Bloc-Examples/BlMouseEventExamples.class.st
src/Bloc/BlElement.class.st

deprecate relocate: into position:

---

src/Bloc-Alexandrie-Tests/BlSpaceFixture.class.st
src/Bloc-DevTool/BlDevCrossover.class.st
src/Bloc-DevTool/BlElementSelection.class.st
src/Bloc-Docs/BlGridLayoutUsageExamples.class.st
src/Bloc-Docs/BlMouseOverOutAndEnterLeaveEventExplanation.class.st
src/Bloc-Examples/BlElementBoundsByScripterExamples.class.st
src/Bloc-Examples/BlElementBoundsExamplesMigrated.class.st
src/Bloc-Examples/BlElementEventExamplesMigrated.class.st
src/Bloc-Examples/BlEventExamples.class.st
src/Bloc-Examples/BlFocusProcessorExamples.class.st
src/Bloc-Examples/BlMouseProcessorClickExamples.class.st
src/Bloc-Examples/BlMouseProcessorEnterLeaveExamples.class.st
src/Bloc-Examples/BlSpaceExamplesMigrated.class.st
src/Bloc-Layout-Examples/BlFlowLayoutCompositionExamples.class.st
src/Bloc-Layout-Examples/BlFrameLayoutCompositionExamplesMigrated.class.st
src/Bloc-Layout-Examples/BlFrameLayoutSingleChildExamples.class.st
src/Bloc-Layout-Examples/BlLinearLayoutUsageExamples.class.st
src/Bloc-Layout-Examples/BlWrapAroundChildrenLayoutExamples.class.st
src/Bloc-Layout-Tests/BlFlowLayoutCompositionSmokeTest.class.st
src/Bloc-Layout-Tests/BlFrameLayoutCompositionTest.class.st
src/Bloc-Layout-Tests/BlFrameLayoutSingleChildTest.class.st
src/Bloc-Layout-Tests/BlLinearLayoutUsageTest.class.st
src/Bloc-Tests/BlElementPositionChangeTest.class.st
src/Bloc-UnitedTests/BlElementBoundsTest.class.st
src/Bloc-UnitedTests/BlElementEventTest.class.st
src/Bloc-UnitedTests/BlSpace2Test.class.st
src/Bloc-UnitedTests/BlTransformationTest.class.st
src/Bloc/BlVisualSelectionHandler.class.st

Fix all the senders of relacate: to use position:

Fix all the senders of relacate: to use position:

---

src/Bloc-Alexandrie/BlCompositeEffect.extension.st

See https://github.com/pharo-graphics/Bloc/issues/253

add alexendrie back-end to draw composite effects

---

src/Bloc-Alexandrie/BAAxisAlignedCompositionLayer.class.st

Fix #288
There is still another bug, I will report in other issue.

Fix bug in composition layer paint

---

src/Bloc-Alexandrie/BAMockedTextMeasurer.class.st
src/Bloc-Alexandrie/BAMockedTextParagraphSpan.class.st
src/Bloc-Alexandrie/BATextElementMockedMeasurer.class.st
src/Bloc-Alexandrie/BATextMeasurer.class.st
src/Bloc-Alexandrie/BATextParagraphLeaf.class.st
src/Bloc-Alexandrie/BATextParagraphSpan.class.st
src/Bloc-Text-Elements/BlTextElement.class.st
src/Bloc-Text-Examples/BlTextParagraphExamples.class.st
src/Bloc-Text/BlTextParagraph.class.st
src/Bloc-Text/BlTextParagraphLine.class.st
src/Bloc-Text/BlTextParagraphMeasurer.class.st
src/Bloc-Text/BlTextParagraphSegment.class.st
src/Bloc-Text/BlTextParagraphSegmentLeaf.class.st
src/Bloc/BlHostTextMeasurer.class.st

* measurer was received as argument but also stored in inst var
* remove create method (it must be new)
* others

Clean up in text package

---

src/Bloc-Layout/BlLinearLayout.class.st
src/Bloc-Layout/BlLinearLayoutHorizontalOrientation.class.st
src/Bloc-Layout/BlLinearLayoutMeasurer.class.st
src/Bloc-Layout/BlLinearLayoutOrientation.class.st
src/Bloc-Layout/BlLinearLayoutVerticalOrientation.class.st
src/Bloc/BlLayoutMatchParentResizer.class.st

add interspacing to add spaces between cell (different from cell spacing which add also a space but including before the first and after the last).

Linear layout

---

src/BlocHost-Morphic/BlMorphicEventHandler.class.st

See: https://github.com/pharo-graphics/Bloc/issues/335

Add empty handler for text edition

---

src/Bloc-Alexandrie/BlElement.extension.st
src/Bloc-UnitedTests/BlBasicTest.class.st

Fix: Converting to Form was cropped when position is not zero

---

src/BaselineOfBloc/BaselineOfBloc.class.st
src/Bloc-Demo/BlDemoPresenter.class.st

Pari programming with Enzo:
- Rename #run into #open which is usually more common for spec
- Add a world menu entry to open the demo in the help menu
- Load the demo browser by default in Bloc

Iteration on demos

---

src/Bloc-Animation/BlAnimation.class.st
src/Bloc-Animation/BlAnimationLoopDoneEvent.class.st
src/Bloc-Animation/BlAnimationStepEvent.class.st
src/Bloc-Animation/BlBaseAnimation.class.st
src/Bloc-Animation/BlColorTransition.class.st
src/Bloc-Animation/BlCompositeAnimation.class.st
src/Bloc-Animation/BlGaussianEffectOpacityAnimation.class.st
src/Bloc-Animation/BlNumberTransition.class.st
src/Bloc-Animation/BlOpacityAnimation.class.st
src/Bloc-Animation/BlParallelAnimation.class.st
src/Bloc-Animation/BlSequentialAnimation.class.st
src/Bloc-Animation/BlTransformAnimation.class.st
src/Bloc-Animation/BlTransition.class.st
src/Bloc-Animation/package.st
src/Bloc-Examples/BlAnimationExamplesTest.class.st

BlBaseAnimation: Multiple steps may have passed!

---

src/BlocHost-OSWindow/BlOSWindowEventHandler.class.st

Use maximize and minimize events (SDL2 host)

---

src/Bloc-Tests/BlAffineTransformationTest.class.st
src/Bloc/BlAffineCompositeTransformation.class.st
src/Bloc/BlMatrixTransformation.class.st
src/Bloc/BlPerspectiveTransformation.class.st
src/Bloc/BlReflectionTransformation.class.st
src/Bloc/BlRotationTransformation.class.st
src/Bloc/BlScalingTransformation.class.st
src/Bloc/BlShearTransformation.class.st
src/Bloc/BlTranslationTransformation.class.st

Add missing equality for transformation

Add equality for transformation

---

src/BlocHost-Morphic/BlMorphicWorldState.class.st

Remove unsent and broken method: assuredCanvas

---

src/Bloc-Tests/BlBackgroundTest.class.st
src/Bloc/BlBackground.class.st
src/Bloc/BlCompositeBackground.class.st
src/Bloc/BlImageBackground.class.st
src/Bloc/BlPaintBackground.class.st

fix: #519 
Add tests for BlBackground with opacity

Issue 0519

---

src/Bloc-Alexandrie-SVG/BASvgPathDrawHandler.class.st
src/Bloc-Alexandrie/BlBezierCurveGeometry.extension.st

Quadratic curve

---

src/Bloc-Scripter/BlDevScripterStepFailureState.class.st
src/Bloc-Scripter/BlDevScripterStepHaltState.class.st
src/Bloc-Scripter/BlDevScripterStepReadyState.class.st
src/Bloc-Scripter/BlDevScripterStepSuccessState.class.st
src/Bloc-Text-Rope/BlRopedText.class.st
src/Bloc-Text-Rope/BlRopedTextIterator.class.st
src/Bloc-Text/BlFontSizeAttribute.class.st
src/Bloc-Text/BlFontWeightAttribute.class.st
src/Bloc-Text/BlSpan.class.st
src/Bloc-Text/BlSubText.class.st
src/Bloc-Text/BlSubTextIterator.class.st
src/Bloc-Text/BlText.class.st
src/Bloc-Text/BlTextBackgroundAttribute.class.st
src/Bloc-Text/BlTextForegroundAttribute.class.st
src/Bloc-Text/BlTextIterator.class.st
src/Bloc-Text/BlTextParagraph.class.st
src/Bloc-Text/BlTextReadStream.class.st
src/Bloc/BlCollectionRope.class.st
src/Bloc/ManifestBloc.class.st

Fix old mentions of Brick classes

---

src/Bloc-DevTool/BlBenchmarkConsole.class.st
src/Bloc-DevTool/BlDevHalosEventListenerExample.class.st
src/Bloc-Infinite/BlOvershootingScroller.class.st
src/Bloc-Tests/BlAbstractEventProcessingTest.class.st
src/Bloc-Tests/BlEventDispatcherTest.class.st
src/Bloc-Tests/BlEventTest.class.st
src/Bloc-Tests/BlKeyboardProcessorTest.class.st
src/Bloc-Tests/BlSpaceTest.class.st
src/Bloc-Tests/BlTestFocusProcessor.class.st
src/Bloc-Tests/BlTestMouseEventProcessor.class.st
src/Bloc/BlBaseEventProcessor.class.st
src/Bloc/BlEvent.class.st
src/Bloc/BlFastForwardedTime.class.st
src/Bloc/BlKeyboardProcessor.class.st
src/Bloc/BlMouseDownEvent.class.st
src/Bloc/BlMouseMoveEvent.class.st
src/Bloc/BlMouseUpEvent.class.st
src/Bloc/BlSpace.class.st
src/Bloc/BlSpaceTaskQueue.class.st
src/Bloc/BlTaskQueue.class.st
src/BlocHost-Morphic/BlMorphicEventHandler.class.st
src/BlocHost-OSWindow/BlOSWindowEventHandler.class.st

- See issue #496
- This includes some related cleaning up (pragmas, reformat)

Ask current time via space's clock

---

src/Bloc/BlParallelUniverse.class.st
src/Bloc/BlSpaceShownEvent.class.st

Initialize BlSpaceShownEvent correctly

---

src/Bloc-Infinite/BlInfiniteLayout.class.st
src/Bloc-Infinite/BlInfiniteLinearLayout.class.st
src/Bloc-Layout-Tests/BlLayoutTest.class.st
src/Bloc-Layout/BlFlowLayout.class.st
src/Bloc-Layout/BlGridLayout.class.st
src/Bloc-Layout/BlGridLayoutImpl.class.st
src/Bloc-Layout/BlLinearLayout.class.st
src/Bloc-Layout/BlOnceLayout.class.st
src/Bloc-Layout/BlSquaredLayout.class.st
src/Bloc-LayoutZoomable/BlZoomableLayout.class.st
src/Bloc/BlColorPaint.class.st
src/Bloc/BlElementGeometry.class.st
src/Bloc/BlGradientPaint.class.st
src/Bloc/BlInsets.class.st
src/Bloc/BlLayout.class.st

Reverts pharo-graphics/Bloc#558

Revert "Equality and hash"

---

src/Bloc/BlMouseProcessor.class.st

these changes were lost during commits of a recent PR

removed last references to dragStartMask

---

src/Bloc-Demo/BlDemoCollector.class.st

This pull request makes BlDemoCollector sort the packages, classes and methods.

Make BlDemoCollector sort the packages, classes and methods

---

src/Bloc-Demo/BlDemoCollector.class.st
src/Bloc-Demo/BlDemoMethodNode.class.st

This pull request extends BlDemoCollector and BlDemoMethodNode to include metaclass methods.

Extend BlDemoCollector and BlDemoMethodNode to include metaclass methods

---

src/Bloc-Text/RBAssignmentToken.extension.st
src/Bloc-Text/RBBinarySelectorToken.extension.st
src/Bloc-Text/RBCommentToken.extension.st
src/Bloc-Text/RBEOFToken.extension.st
src/Bloc-Text/RBErrorToken.extension.st
src/Bloc-Text/RBIdentifierToken.extension.st
src/Bloc-Text/RBKeywordToken.extension.st
src/Bloc-Text/RBLiteralArrayToken.extension.st
src/Bloc-Text/RBLiteralToken.extension.st
src/Bloc-Text/RBNumberLiteralToken.extension.st
src/Bloc-Text/RBPatternBlockToken.extension.st
src/Bloc-Text/RBSpecialCharacterToken.extension.st
src/Bloc-Text/RBToken.extension.st

Remove unused acceptVisitor: extensions in RB tokens

---

src/BlocHost-Morphic/BlMorphicHostSpace.class.st
src/BlocHost-Morphic/BlMorphicWindowHostSpace.class.st

Do not reference World global

---

src/Bloc/BlBubblingEventDispatcher.class.st
src/Bloc/BlDirectEventDispatcher.class.st
src/Bloc/BlElementEventDispatcher.class.st
src/Bloc/BlEventDispatcher.class.st
src/Bloc/BlEventDispatcherChain.class.st
src/Bloc/BlEventDispatcherEmptyChain.class.st

Clean up event handling

---

src/Bloc-Alexandrie/BlGaussianShadowEffect.extension.st
src/Bloc/BlGaussianShadowEffect.class.st

(To be reverted when has a fix https://github.com/pharo-graphics/Bloc/issues/543)

Gaussian shadow: cache the alpha surface

---

src/Bloc-Text-Tests/BlRopedTextTest2.class.st
src/Bloc-Text/BlText.class.st

This makes it work on Pharo 13, where it was an signalling error.
Fixes #433

Deprecate BlText>>when:do: and upgrade a couple of uses

---

src/Bloc-Animation/BlBaseAnimation.class.st
src/Bloc-Examples/BlAnimationExamplesTest.class.st

Animations: tolerate redundant #start and #stop

---

src/Bloc-DevTool/BlDevElement.class.st
src/Bloc-Examples/BlGeometryVisualAndLayoutBoundsExamples.class.st

Migrate BlDevElement to Bloc-Alexandrie

---

src/Bloc/BlSpace.class.st
src/BlocHost-Morphic/BlMorphicHostSpace.class.st
src/BlocHost-Morphic/BlMorphicWindowHostSpace.class.st

Implement some explicit requirements on Morphic host & fix some space properties for all hosts

---

src/Bloc-Examples/BlEventCountingElement.class.st
src/Bloc-Examples/BlMouseProcessorClickTest.class.st
src/Bloc-Tests/BlMouseProcessorTest.class.st
src/Bloc/BlMouseProcessor.class.st

Mouse processor: Fix test and clean up code

---

src/Bloc/BlElement.class.st
src/Bloc/BlSpace.class.st

Delete showSpace: in BlElement and BlSpace

---

src/Bloc/BlSpace.class.st

[WIP] Reduce object creation to reduce Impact in the GC

---

src/Bloc-Examples/BlAnimationExamplesTest.class.st
src/Bloc-Scalable-Examples/BlScalableElementExamples.class.st

Increase precision of expected Floats in some tests

---

src/Bloc/Context.extension.st

In Pharo 13, Context doesn't understand #outerMostContext anymore.

---

src/Bloc/BlElementVectorGeometry.class.st

Optimize BlElementVectorGeometry>>#initialize

---

src/Bloc-Layout/BlGridLayoutImpl.class.st

Remove some unneeded temporary creations of Interval

---

src/Bloc-Layout/BlFitChildrenLayout.class.st
src/Bloc-Layout/BlFitLayout.class.st
src/Bloc-Layout/BlFlowLayoutMeasurer.class.st
src/Bloc-Layout/BlGridLayoutImpl.class.st
src/Bloc-Layout/BlLinearLayoutMeasurer.class.st
src/Bloc-Layout/BlProportionalLayout.class.st
src/Bloc-Layout/BlWrapAroundChildrenLayout.class.st
src/Bloc-Scalable/BlScalableElement.class.st
src/Bloc-Tests/BlBoundsTest.class.st
src/Bloc/BlBounds.class.st
src/Bloc/BlExtentMeasurementSpec.class.st
src/Bloc/BlLayout.class.st

Reduce generation of some very temporary Points in layouts

---

src/Bloc-Text-Tests/BlPharoCodeStylerTest.class.st
src/Bloc-Text/BlSHRBTextStyler.class.st

Fix BlSHRBTextStyler to work on Pharo 12 and 13. Add 2 tests.

---

src/BlocHost-OSWindow-SDL2/BlOSWindowSDL2Host.class.st

Fixes #507
A fix of @rvillemeur that we forgot to PR!

Center the space in SDL host if no position was specified

---

src/Bloc-Rules/ReBlocDoNotSendForceLayoutRule.class.st
src/Bloc-Rules/ReBlocWidthShouldNotBeOverriddenRule.class.st

Convert 2 rules in Bloc-Rules package to Pharo >= 13

---

src/Bloc-DevTool/BlSpaceStatistics.class.st
src/Bloc-DevTool/BlSpaceStatisticsWindow.class.st

I propose to change how information is printed, added a couple of lines, as well as reducing the initial window size. Opinions?

Pass on space statistics

---

src/Bloc-Alexandrie/BlStadiumGeometry.extension.st
src/Bloc-Alexandrie/BlTriangleGeometry.extension.st

Improvement on gradient shadow

---

src/Bloc-Demo/BlDemoPresenter.class.st
src/Bloc/Bloc.class.st

See: https://github.com/pharo-graphics/Bloc/issues/454

Add a Bloc entry in the World Menu + github web entry
